### PR TITLE
Pma new sponsors

### PR DESCRIPTION
**Pull request by pm-araujo**
Contains logo images for two new sponsors and stylings for centering the logos;
New class **SponsorGrid-row** created to achieve this effect, the idea seems to be to group logos 3by3, when width allows it;

### CODE REVIEW

**Comment by pm-araujo** [comment]
There's some resizing problems occurring, namely with the StartupBraga logo img;

**Comment by pm-araujo** [comment]
Resizing issue fixed, ready for code review

**Comment by pm-araujo** [comment]
refactored according to suggestions, waiting on code review

**Comment by frm** [comment]
👍

**Pull request merged**
